### ISSUE TITLE
mac dmg 激活问题

### ISSUE THREAD

**Issue by busyfree** [h3110w0r1d-y/BurpLoaderKeygen#16]
BP 版本： burpsuite_pro_macos_x64_v2022_3_9.dmg
```
❯ java -version
java version "1.8.0_331"
Java(TM) SE Runtime Environment (build 1.8.0_331-b09)

```

运行报错

```
❯ java -javaagent:BurpLoaderKeygen.jar -noverify -jar burpsuite_pro.jar
    ____                      __                    __             __ __
   / __ )__  ___________     / /   ____  ____ _____/ /__  _____   / //_/__  __  ______ ____  ____
  / __  / / / / ___/ __ Ø   / /   / __ Ø/ __ `/ __  / _ Ø/ ___/  / ,< / _ Ø/ / / / __ `/ _ Ø/ __ Ø
 / /_/ / /_/ / /  / /_/ /  / /___/ /_/ / /_/ / /_/ /  __/ /     / /ø /  __/ /_/ / /_/ /  __/ / / /
/_____/Ø__,_/_/  / .___/  /_____/Ø____/Ø__,_/Ø__,_/Ø___/_/     /_/ ø_Ø___/Ø__, /Ø__, /Ø___/_/ /_/
                /_/                                                      /____//____/
Github:https://github.com/h3110w0r1d-y/BurpLoaderKeygen 商业使用请购买正版软件！
Error: A JNI error has occurred, please check your installation and try again
Exception in thread "main" java.lang.UnsupportedClassVersionError: burp/StartBurp has been compiled by a more recent version of the Java Runtime (class file version 53.0), this version of the Java Runtime only recognizes class file versions up to 52.0
	at java.lang.ClassLoader.defineClass1(Native Method)
	at java.lang.ClassLoader.defineClass(ClassLoader.java:756)
	at java.security.SecureClassLoader.defineClass(SecureClassLoader.java:142)
	at java.net.URLClassLoader.defineClass(URLClassLoader.java:473)
	at java.net.URLClassLoader.access$100(URLClassLoader.java:74)
	at java.net.URLClassLoader$1.run(URLClassLoader.java:369)
	at java.net.URLClassLoader$1.run(URLClassLoader.java:363)
	at java.security.AccessController.doPrivileged(Native Method)
	at java.net.URLClassLoader.findClass(URLClassLoader.java:362)
	at java.lang.ClassLoader.loadClass(ClassLoader.java:418)
	at sun.misc.Launcher$AppClassLoader.loadClass(Launcher.java:355)
	at java.lang.ClassLoader.loadClass(ClassLoader.java:351)
	at sun.launcher.LauncherHelper.checkAndLoadMain(LauncherHelper.java:601)
```

**Comment by h3110w0r1d-y** [comment]
请使用jar版本

**Comment by h3110w0r1d-y** [comment]
下载1.4版本，之前的版本不支持java8

**Comment by busyfree** [comment]
OK，感谢。
