### ISSUE TITLE
kali linux 2022.3 使用问题

### ISSUE THREAD

**Issue by Trapshell** [h3110w0r1d-y/BurpLoaderKeygen#18]
`java -jar ./BurpLoaderKeygen.jar`
Picked up _JAVA_OPTIONS: -Dawt.useSystemAAFontSettings=on -Dswing.aatext=true
Exception in thread "main" java.lang.ArrayIndexOutOfBoundsException: Index 1 out of bounds for length 1
        at com.h3110w0r1d.burploaderkeygen.KeygenForm.getJavaVersion(KeygenForm.java:60)
        at com.h3110w0r1d.burploaderkeygen.KeygenForm.GetCMD(KeygenForm.java:103)
        at com.h3110w0r1d.burploaderkeygen.KeygenForm.main(KeygenForm.java:286)

之前没出现这个问题过，换了java17和18均报错了。:see_no_evil:

这个问题已经解决：移至☞与java同目录（估计是没办法识别linux设置的java环境变量）:bug:

**Comment by h3110w0r1d-y** [comment]
fixed

**Comment by h3110w0r1d-y** [comment]
@Trapshell 刚刚发的那个没修好，现在又重新发了一遍，应该没问题了😅
