### ISSUE TITLE
请问能否添加linux适配？

### ISSUE THREAD

**Issue by iPixelOldC** [h3110w0r1d-y/BurpLoaderKeygen#4]
最新版貌似是写死了只能windows用啊,其他系统没cmd QAQ 能否增加个bash支持呢？这样Linux和Mac OS就应该同时被支持了吧
我目前就是用1.1的版本，写了个shell脚本运行，不过没汉化，如果您这能增加适配就好了

```
Exception in thread "main" java.lang.NullPointerException: Cannot invoke "String.equals(Object)" because the return value of "com.h3110w0r1d.burploaderkeygencn.KeygenForm.readProperty(String)" is null
	at com.h3110w0r1d.burploaderkeygencn.KeygenForm.GetCMD(KeygenForm.java:72)
	at com.h3110w0r1d.burploaderkeygencn.KeygenForm.main(KeygenForm.java:209)
```

**Comment by iPixelOldC** [comment]
嘛，BurpLoaderKeygen.jar这个文件我使用正常的，我这里报错是BurpLoaderKeygenCN.jar那个可以汉化的Jar。我自己的脚本无非就是BurpLoaderKeygen里面生成的命令，然后加上绝对路径（因为我本机jre版本不够，就用这软件自带的jre）





------------------ 原始邮件 ------------------
发件人: h3110w0r1d ***@***.***&gt;
发送时间: 2021年8月27日 23:52
收件人: h3110w0r1d-y/BurpLoaderKeygen ***@***.***&gt;
抄送: iPixelOldC ***@***.***&gt;, Author ***@***.***&gt;
主题: 回复：[h3110w0r1d-y/BurpLoaderKeygen] 请问能否添加linux适配？ (#4)






勾选auto run之后直接双击BurpLoaderKeygen.jar就能启动burp了，在linux下也可以的。如果非要写脚本的话就直接写java -jar BurpLoaderKeygen.jar或者写Loader Command里面的那行命令

**Comment by h3110w0r1d-y** [comment]
刚刚测试过了，可以正常使用呀
![image](https://user-images.githubusercontent.com/52311174/131204522-3c589b3a-cc1c-4707-803e-81f45e4222f8.png)

把你写的脚本，完整的报错截图发一下看看

**Comment by iPixelOldC** [comment]
```
oldc@arcoi3: /home/oldc/Softs/BurpSuitePro
➜   ls
 burpbrowser               BurpLoaderKeygenCn.jar   BurpSuitePro                       burpsuite_pro.jar        config.cfg   start.sh
 BurpLoaderKeygen-cn.jar   BurpLoaderKeygen.jar    'Burp Suite Professional.desktop'   BurpSuitePro.vmoptions   jre          uninstall
oldc@arcoi3: /home/oldc/Softs/BurpSuitePro
➜   ./jre/bin/java -jar BurpLoaderKeygenCn.jar
Exception in thread "main" java.lang.NullPointerException: Cannot invoke "String.equals(Object)" because the return value of "com.h3110w0r1d.burploaderkeygencn.KeygenForm.readProperty(String)" is null
	at com.h3110w0r1d.burploaderkeygencn.KeygenForm.GetCMD(KeygenForm.java:72)
	at com.h3110w0r1d.burploaderkeygencn.KeygenForm.main(KeygenForm.java:209)
```

**Comment by iPixelOldC** [comment]
```
oldc@arcoi3: /home/oldc/Softs/BurpSuitePro
➜   ls
 burpbrowser               BurpLoaderKeygenCn.jar   BurpSuitePro                       burpsuite_pro.jar        config.cfg   start.sh
 BurpLoaderKeygen-cn.jar   BurpLoaderKeygen.jar    'Burp Suite Professional.desktop'   BurpSuitePro.vmoptions   jre          uninstall
oldc@arcoi3: /home/oldc/Softs/BurpSuitePro
➜   ./jre/bin/java -jar BurpLoaderKeygenCn.jar
Exception in thread "main" java.lang.NullPointerException: Cannot invoke "String.equals(Object)" because the return value of "com.h3110w0r1d.burploaderkeygencn.KeygenForm.readProperty(String)" is null
	at com.h3110w0r1d.burploaderkeygencn.KeygenForm.GetCMD(KeygenForm.java:72)
	at com.h3110w0r1d.burploaderkeygencn.KeygenForm.main(KeygenForm.java:209)
```
BurpLoaderKeygen.jar我是能正常使用的，包括直接用`./jre/bin/java -jar BurpLoaderKeygen.jar`也能打开注册机的界面，而`./jre/bin/java -jar BurpLoaderKeygenCn.jar`打开都打开不了。

**Comment by iPixelOldC** [comment]
```
➜   uname -a                        
Linux arcoi3 5.13.12-zen1-1-zen #1 ZEN SMP PREEMPT Wed, 18 Aug 2021 20:49:05 +0000 x86_64 GNU/Linux
```
系统版本 ArcoLinux + i3DE

**Comment by iPixelOldC** [comment]
能否发下，您这图那个命令呢？我这边想试试。以及我刚刚瞅了眼我这里的BurpSuitePro文件，里面其实就是个shell脚本。我可以尝试把你给的命令里的jvm参数，全部加到`BurpSuitePro.vmoptions`文件中，再双击启动BurpSuitePro,应该是也能达到使用脚本的效果，并且这个应该是全平台通用的吧？因为隔壁SmartSVN和SmartGit这两java写的软件，用的注册文件的参数就是加到vmoptions里面的（和你这个的参数差不多)

> 刚刚测试过了，可以正常使用呀
> ![image](https://user-images.githubusercontent.com/52311174/131204522-3c589b3a-cc1c-4707-803e-81f45e4222f8.png)
> 
> 把你写的脚本，完整的报错截图发一下看看

**Comment by iPixelOldC** [comment]
```
oldc@arcoi3: /home/oldc/Softs/BurpSuitePro
➜   cat BurpSuitePro.vmoptions
# Enter one VM parameter per line
# For example, to adjust the maximum memory usage to 512 MB, uncomment the following line:
# -Xmx512m
# To include another file, uncomment the following line:
# -include-options [path to other .vmoption file]

-javaagent:/home/oldc/Softs/BurpSuitePro/BurpLoaderKeygen.jar
-noverify
-XX:MaxRAMPercentage=50
-include-options user.vmoptions
```
刚刚试了试，恩，这样做破解也是可以启用的，还是直接用软件安装包安装时生成的.desktop文件打开软件

**Comment by iPixelOldC** [comment]
额，咋被close了，这个问题没被解决啊…
